### ISSUE TITLE
Q's related to linux drivers

### ISSUE THREAD

**Issue by jodavaho** [Sensirion/linux-sps30#1]
- Does the sensor still auto-clean according to the pre-set duration? Should I write to `start_cleaning` periodically? What should I write?
- Can the sensor sleep between reads? or can sleep be commanded?
- If I read from the `massconcentration` files, does that interrupt cleaning? If so, how can I synchronize my monitoring to allow cleaning?
  - Perhaps space the reads long enough to allow cleaning? How long does it clean then?

**Comment by rnestler** [comment]
Hi @jodavaho 

Please note that this is just a back port of the driver from the official kernel driver, which is not maintained by Sensirion.

> Does the sensor still auto-clean according to the pre-set duration?

The sensor will do the auto-clean according to the configured auto cleaning interval. As far as I can see the driver allows to set this, so it should work. 

> Should I write to start_cleaning periodically?

Not if you enabled the auto-clean.

> Can the sensor sleep between reads? or can sleep be commanded?

As far as I can tell sleep/wakeup isn't implemented in this driver. See https://github.com/Sensirion/embedded-sps for a driver which works in user-space and has sleep/wakeup implemented.

Note that sleep is possible between measurements, but that the sensor needs some warmup time until it gives you proper results. So only use sleep if you have long intervals between measurements.

> If I read from the massconcentration files, does that interrupt cleaning? If so, how can I synchronize my monitoring to allow cleaning? 

See the [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.6_Particulate_Matter/Datasheets/Sensirion_PM_Sensors_Datasheet_SPS30.pdf):
> Measurement values are not updated while the fan-cleaning is running. 

So you will just read the same value during fan-cleaning.

**Comment by jodavaho** [comment]
@rnestler Thank you!
